### ISSUE TITLE
Helper for "Shell Mode"

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/extended-json#3]
Want to be able to take any string that a mongo instance spits and make it structured data (eg rs.status()).  Not sure if this should go here or imlucas/mongodb-log

```javascript
var dateRegExp = /ISODate\(\"([\w\d\-\:]+)\"\)/g,
  dateMatches,
  timestampRegExp = /Timestamp\((\d+)\,\s?(\d+)\)/,
  timestampMatches;

while ((dateMatches = dateRegExp.exec(raw)) !== null){
  raw = raw.replace(dateMatches[0], '{"$date": '+new Date(dateMatches[1]).getTime()+'}');
}
while ((timestampMatches = timestampRegExp.exec(raw)) !== null){
  raw = raw.replace(timestampMatches[0], '{"$timestamp": {"$t": '+ timestampMatches[1] +', "$i": '+timestampMatches[2]+'}}');
}
```

cc @rueckstiess

**Comment by imlucas** [comment]
Can just merge https://github.com/rueckstiess/mongodb-log2ejson into mongodb-extended-json

**Comment by graemian** [comment]
Thank you for this. I've been trying to find a way to eat this Mongo "shitbag" JSON, and that snippet of yours did the trick ;-)

I suggest you add the method EJSON.eatMongoShitBagJson, or rather EJSON.parseShellModeJson ;-)

**Comment by rueckstiess** [comment]
Unfortunately, it's even worse. What MongoDB prints into the log files is **not the same** as _shell mode_ or _strict mode_ extended json (see [SERVER-16618](https://jira.mongodb.org/browse/SERVER-16618) ticket).

Example (MongoDB 3.1.3)

1. Strict mode: `{ "$timestamp": { "t": 1435384146, "i": 15 } }`
2. Shell mode: `Timestamp(1435384146, 15)`
3. Log format: `Timestamp 1435384146000|15`

[mongodb-log2ejson](https://github.com/rueckstiess/mongodb-log2ejson) converts log format to strict mode ejson (3. --> 1.)

To cover all cases, we need:

- parse from strict mode   (current `EJSON.parse()`)
- parse from shell mode
- parse from log mode

which all return a javascript object with bson types as values. 

Further:

- serialize to strict mode (current `EJSON.serialize()`)
- serialize to shell mode
- serialize to log mode

which outputs strings.

**Comment by rueckstiess** [comment]
@imlucas any suggestions for public API for this?

- `EJSON.parse(text, reviver, mode)`
- `EJSON.stringify(value, replacer, space, mode)`

Where mode can be `strict` (default), `shell`, `log` ?

Or separate methods?

- `EJSON.parse(text, reviver)`   for strict mode
- `EJSON.parseFromShell(text, reviver)`   for shell mode
- `EJSON.parseFromLog(text, revivier)`  for log mode
- `EJSON.stringify(value, replacer, space)`   for strict mode
- `EJSON.stringifyToShell(value, replacer, space)` for shell mode
- `EJSON.stringifyToLog(value, replacer, space)` for log mode

Both won't break existing API.

**Comment by rueckstiess** [comment]
Because neither shell nor log mode are actual parsable json, we need to regex.replace() the strings beforehand instead of using a `reviver` function on `EJSON.parse()`. On the way out, however, we could do either:

1. Use a `replacer` function in `EJSON.stringify()`, see [here](http://mdn.io/JSON.stringify#The_replacer_parameter)
2. `.stringify()` as usual and then regex again to go from strict to shell or log

**Comment by kangas** [comment]
My recommendation to Thomas:

- Let's merge in your parsing enhancements
- Forget about stringifying to shell/log formats for now
- When we have immediate use cases for stringifying to shell/log formats that cannot be addressed through other means, then add new EJSON methods (e.g. stringifyToShell). Don't overload the existing .stringify method because the implementation will be different and probably ugly.

I see this as a request to process (parse messy formats) -> (clean) -> (render messy formats). Parsing from the messy formats is a win, but rendering back to messy seems like a distraction.

**Comment by kangas** [comment]
Re: rendering to log, I would rather invest energy in getting the server to log things in less absurd formats.

**Comment by rueckstiess** [comment]
Yep I agree with your recommendations and will do exactly that. Just cleaning up the changes now and making PR for review.
